### Update Event without Image (Partial Update)
PUT http://localhost:3000/api/v1/events/674861b0f9c2281eb7e6643d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RyYWNoaWRAZXhhbXBsZS5jb20iLCJzdWIiOiI2NzQ4MmM3YmNjN2VlYzcxMDEyN2YxYWEiLCJpYXQiOjE3MzI3ODY3ODEsImV4cCI6MTczMjgwNDc4MX0.KQW9k4P-jn2I7mhquqeLqY4zGc5aVO2cxiuaUveE6hI
Content-Type: application/json

{
    "name": "Updated Event Name Only",
    "capacity": 1000
}

### Update Event Only Description
PUT http://localhost:3000/api/v1/events/674861b0f9c2281eb7e6643d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RyYWNoaWRAZXhhbXBsZS5jb20iLCJzdWIiOiI2NzQ4MmM3YmNjN2VlYzcxMDEyN2YxYWEiLCJpYXQiOjE3MzI3ODY3ODEsImV4cCI6MTczMjgwNDc4MX0.KQW9k4P-jn2I7mhquqeLqY4zGc5aVO2cxiuaUveE6hI
Content-Type: application/json

{
    "description": "This is just updating the description of the event. It needs to be at least twenty characters long to pass validation."
}