export enum NotificationType {
  EVENT_CREATED = 'EVENT_CREATED',
  EVENT_UPDATED = 'EVENT_UPDATED',
  EVENT_DELETED = 'EVENT_DELETED',
  EVENT_APPROVAL_REQUIRED = 'EVENT_APPROVAL_REQUIRED',
  EVENT_APPROVED = 'EVENT_APPROVED',
  EVENT_REJECTED = 'EVENT_REJECTED',
  TICKET_PURCHASED = 'TICKET_PURCHASED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  USER_REGISTERED = 'USER_REGISTERED',
  SYSTEM = 'SYSTEM',
}
